#! /bin/sh

case "$1" in
	start)
		echo "Starting modules"
		scull_load
		#start-stop-daemon -S -n scull_load -a /usr/bin/scull_load
		;;
	stop)
		echo "Stopping modules"
		#start-stop-daemon -K -n scull_unload
		scull_unload
		;;
	*)
		echo "Usage $0 {start|stop}"
		exit 1
esac
exit 0
